name: "string-tokeniser"
description: "Finds and replaces strings"
author: "Scott Walker"
inputs:
  files:
    description: "A glob of files search through"
    default: "**"
    required: false
  prefix:
    description: "The values that prefix the string"
    default: "#{"
    required: false
  suffix:
    description: "The values that suffix the string"
    default: "}#"
    required: false
runs:
  using: "docker"
  image: "docker://ghcr.io/scott-david-walker/tokeniser:0.0.2"