name: Build
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install dependencies
        working-directory: "src/main"
        run: |
          go get .

      - name: Build
        working-directory: "src/main"
        run: go build -v

      - name: Test
        working-directory: "src/main"
        run: go test -v